export const seriesWallItems = [
  {
    name: "765PRO ALLSTARS",
    background: "bg-franchise-765",
    image: "/brand/series/wall/765pro.webp",
    icon: "/brand/series/wall/765pro.webp",
    iconWidth: 585,
    iconHeight: 500,
    href: "/works/765",
  },
  {
    name: "CINDERELLA GIRLS",
    background: "bg-franchise-cg",
    image: "/brand/series/wall/cinderella-girls.webp",
    icon: "/brand/series/wall/cinderella-girls.webp",
    iconWidth: 585,
    iconHeight: 500,
    href: "/works/cg",
  },
  {
    name: "MILLION LIVE!",
    background: "bg-franchise-ml",
    image: "/brand/series/wall/million-live.webp",
    icon: "/brand/series/wall/million-live.webp",
    iconWidth: 585,
    iconHeight: 500,
    href: "/works/ml",
  },
  {
    name: "SideM",
    background: "bg-franchise-sidem",
    image: "/brand/series/wall/sidem.webp",
    icon: "/brand/series/wall/sidem.webp",
    iconWidth: 585,
    iconHeight: 500,
    href: "/works/sidem",
  },
  {
    name: "SHINY COLORS",
    background: "bg-franchise-sc",
    image: "/brand/series/wall/shiny-colors.webp",
    icon: "/brand/series/wall/shiny-colors.webp",
    iconWidth: 585,
    iconHeight: 500,
    href: "/works/sc",
  },
  {
    name: "学园偶像大师",
    background: "bg-franchise-gk",
    image: "/brand/series/wall/gakuen.webp",
    icon: "/brand/series/wall/gakuen.webp",
    iconWidth: 585,
    iconHeight: 500,
    href: "/works/gakuen",
  },
] as const
