// Generated by scripts/contracts/compile-frontend-route-metadata.mjs.
// Do not edit by hand.

export const FRONTEND_PRERENDERED_ROUTES = Object.freeze([
    Object.freeze(['/', 'index.html'] as const),
    Object.freeze(['/about', 'about/index.html'] as const),
    Object.freeze(['/events', 'events/index.html'] as const),
    Object.freeze(['/recommendations', 'recommendations/index.html'] as const),
    Object.freeze(['/live', 'live/index.html'] as const),
    Object.freeze(['/community', 'community/index.html'] as const),
    Object.freeze(['/account/login', 'account/login/index.html'] as const),
    Object.freeze(['/account/register', 'account/register/index.html'] as const),
    Object.freeze(['/account/password-reset', 'account/password-reset/index.html'] as const),
    Object.freeze(['/account/security', 'account/security/index.html'] as const),
    Object.freeze(['/community/exchange', 'community/exchange/index.html'] as const),
    Object.freeze(['/community/cards', 'community/cards/index.html'] as const),
    Object.freeze(['/producer-map', 'producer-map/index.html'] as const),
    Object.freeze(['/tier-list', 'tier-list/index.html'] as const),
    Object.freeze(['/works', 'works/index.html'] as const),
    Object.freeze(['/works/765', 'works/765/index.html'] as const),
    Object.freeze(['/works/cg', 'works/cg/index.html'] as const),
    Object.freeze(['/works/ml', 'works/ml/index.html'] as const),
    Object.freeze(['/works/sidem', 'works/sidem/index.html'] as const),
    Object.freeze(['/works/sc', 'works/sc/index.html'] as const),
    Object.freeze(['/works/gakuen', 'works/gakuen/index.html'] as const),
    Object.freeze(['/works/games', 'works/games/index.html'] as const),
    Object.freeze(['/works/wows', 'works/wows/index.html'] as const),
    Object.freeze(['/wiki', 'wiki/index.html'] as const),
    Object.freeze(['/wiki/modern', 'wiki/modern/index.html'] as const),
    Object.freeze(['/story', 'story/index.html'] as const),
    Object.freeze(['/story/modern', 'story/modern/index.html'] as const),
    Object.freeze(['/chronicle', 'chronicle/index.html'] as const),
    Object.freeze(['/wiki/classic', 'wiki/classic/index.html'] as const),
    Object.freeze(['/story/classic', 'story/classic/index.html'] as const),
] as const);

export const FRONTEND_SPA_FALLBACK_PATTERNS = Object.freeze([
    Object.freeze({ id: 'admin', match: 'prefix', path: '/admin', segments: Object.freeze(['admin'] as const) } as const),
    Object.freeze({ id: 'events/:eventId', match: 'prefix', path: '/events', segments: Object.freeze(['events'] as const), segmentCount: 2 } as const),
    Object.freeze({ id: 'community/exchange/me', match: 'exact', path: '/community/exchange/me', segments: Object.freeze(['community', 'exchange', 'me'] as const) } as const),
    Object.freeze({ id: 'community/exchange/offices/:officeSlug', match: 'prefix', path: '/community/exchange/offices', segments: Object.freeze(['community', 'exchange', 'offices'] as const), segmentCount: 4 } as const),
    Object.freeze({ id: 'information/:contentId', match: 'prefix', path: '/information', segments: Object.freeze(['information'] as const), segmentCount: 2 } as const),
    Object.freeze({ id: 'chronicle/:activityId', match: 'prefix', path: '/chronicle', segments: Object.freeze(['chronicle'] as const), segmentCount: 2 } as const),
] as const);
