-- ims:migration-phase: pre-data

CREATE TABLE public.ims_data_migrations (
    source_sha256 TEXT PRIMARY KEY,
    source_filename TEXT NOT NULL,
    source_size_bytes BIGINT NOT NULL CHECK (source_size_bytes >= 0),
    row_counts JSONB NOT NULL,
    source_foreign_key_violations JSONB NOT NULL,
    imported_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public.news (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT,
    image TEXT,
    thumbnail TEXT,
    content TEXT,
    date TEXT,
    author TEXT
);

CREATE TABLE public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT UNIQUE,
    password TEXT,
    dept TEXT,
    producername TEXT
);

CREATE TABLE public.logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT,
    producername TEXT,
    action TEXT,
    target TEXT,
    ip TEXT,
    time TEXT
);

CREATE TABLE public.cards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image1_url TEXT NOT NULL,
    image2_url TEXT NOT NULL,
    hash1 TEXT,
    hash2 TEXT,
    ip TEXT,
    status TEXT DEFAULT 'pending',
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX cards_hashes_idx ON public.cards (hash1, hash2);
CREATE INDEX cards_status_id_idx ON public.cards (status, id DESC);

CREATE TABLE public.events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT,
    name TEXT,
    contact TEXT,
    image_url TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- The legacy foreign key is added after the import so historical orphan rows
-- can be preserved while all new writes are still checked.
CREATE TABLE public.card_emojis (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_id BIGINT NOT NULL,
    emoji TEXT NOT NULL,
    count INTEGER DEFAULT 1,
    CONSTRAINT card_emojis_card_id_emoji_key UNIQUE (card_id, emoji)
);

CREATE TABLE public.agencies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    name_cn TEXT NOT NULL,
    color TEXT NOT NULL
);

CREATE TABLE public.idols (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agency_id BIGINT NOT NULL,
    name_cn TEXT NOT NULL,
    folder_name TEXT NOT NULL,
    color TEXT NOT NULL,
    CONSTRAINT idols_agency_id_fkey
        FOREIGN KEY (agency_id) REFERENCES public.agencies(id)
);

CREATE INDEX idols_agency_id_idx ON public.idols (agency_id);
CREATE INDEX idols_agency_name_idx ON public.idols (agency_id, name_cn);

CREATE TABLE public.theme_colors (
    name TEXT PRIMARY KEY,
    color TEXT NOT NULL
);

CREATE TABLE public."765_stories" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idol_id BIGINT NOT NULL REFERENCES public.idols(id),
    category TEXT NOT NULL,
    card_name TEXT NOT NULL,
    up_name TEXT,
    video_title TEXT,
    url TEXT,
    subtitle TEXT,
    image_file TEXT
);

CREATE TABLE public."876_stories" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idol_id BIGINT NOT NULL REFERENCES public.idols(id),
    category TEXT NOT NULL,
    card_name TEXT NOT NULL,
    up_name TEXT,
    video_title TEXT,
    url TEXT,
    subtitle TEXT,
    image_file TEXT
);

CREATE TABLE public.cg_stories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idol_id BIGINT NOT NULL REFERENCES public.idols(id),
    category TEXT NOT NULL,
    card_name TEXT NOT NULL,
    up_name TEXT,
    video_title TEXT,
    url TEXT,
    subtitle TEXT,
    image_file TEXT
);

CREATE TABLE public.ml_stories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idol_id BIGINT NOT NULL REFERENCES public.idols(id),
    category TEXT NOT NULL,
    card_name TEXT NOT NULL,
    up_name TEXT,
    video_title TEXT,
    url TEXT,
    subtitle TEXT,
    image_file TEXT
);

CREATE TABLE public.sidem_stories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idol_id BIGINT NOT NULL REFERENCES public.idols(id),
    category TEXT NOT NULL,
    card_name TEXT NOT NULL,
    up_name TEXT,
    video_title TEXT,
    url TEXT,
    subtitle TEXT,
    image_file TEXT
);

CREATE TABLE public.sc_stories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idol_id BIGINT NOT NULL REFERENCES public.idols(id),
    category TEXT NOT NULL,
    card_name TEXT NOT NULL,
    up_name TEXT,
    video_title TEXT,
    url TEXT,
    subtitle TEXT,
    image_file TEXT
);

CREATE TABLE public.gk_stories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idol_id BIGINT NOT NULL REFERENCES public.idols(id),
    category TEXT NOT NULL,
    card_name TEXT NOT NULL,
    up_name TEXT,
    video_title TEXT,
    url TEXT,
    subtitle TEXT,
    image_file TEXT
);

CREATE INDEX "765_stories_idol_id_idx" ON public."765_stories" (idol_id);
CREATE INDEX "765_stories_group_idx"
    ON public."765_stories" (idol_id, category, card_name);
CREATE INDEX "876_stories_idol_id_idx" ON public."876_stories" (idol_id);
CREATE INDEX "876_stories_group_idx"
    ON public."876_stories" (idol_id, category, card_name);
CREATE INDEX cg_stories_idol_id_idx ON public.cg_stories (idol_id);
CREATE INDEX cg_stories_group_idx ON public.cg_stories (idol_id, category, card_name);
CREATE INDEX ml_stories_idol_id_idx ON public.ml_stories (idol_id);
CREATE INDEX ml_stories_group_idx ON public.ml_stories (idol_id, category, card_name);
CREATE INDEX sidem_stories_idol_id_idx ON public.sidem_stories (idol_id);
CREATE INDEX sidem_stories_group_idx ON public.sidem_stories (idol_id, category, card_name);
CREATE INDEX sc_stories_idol_id_idx ON public.sc_stories (idol_id);
CREATE INDEX sc_stories_group_idx ON public.sc_stories (idol_id, category, card_name);
CREATE INDEX gk_stories_idol_id_idx ON public.gk_stories (idol_id);
CREATE INDEX gk_stories_group_idx ON public.gk_stories (idol_id, category, card_name);
