-- ims:migration-phase: post-data

CREATE TABLE public.wiki_story_cards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agency_id BIGINT NOT NULL,
    idol_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    card_name TEXT NOT NULL,
    subtitle TEXT,
    image_file TEXT,
    display_order INTEGER NOT NULL CHECK (display_order >= 0),
    UNIQUE (id, agency_id),
    UNIQUE (agency_id, idol_id, category_id, card_name),
    FOREIGN KEY (agency_id, idol_id, category_id)
        REFERENCES public.wiki_idol_categories(agency_id, idol_id, category_id)
        ON DELETE CASCADE
);

CREATE INDEX wiki_story_cards_agency_idol_idx
    ON public.wiki_story_cards(agency_id, idol_id, display_order);
CREATE INDEX wiki_story_cards_category_idx
    ON public.wiki_story_cards(category_id);
CREATE INDEX wiki_story_cards_background_idx
    ON public.wiki_story_cards(category_id, id) WHERE image_file IS NOT NULL;

CREATE TABLE public.wiki_story_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agency_id BIGINT NOT NULL,
    card_id BIGINT NOT NULL,
    up_name TEXT,
    video_title TEXT,
    url TEXT,
    display_order INTEGER NOT NULL CHECK (display_order >= 0),
    legacy_table TEXT,
    legacy_id BIGINT,
    legacy_subtitle TEXT,
    legacy_image_file TEXT,
    UNIQUE (card_id, display_order),
    UNIQUE (legacy_table, legacy_id),
    CHECK ((legacy_table IS NULL) = (legacy_id IS NULL)),
    FOREIGN KEY (card_id, agency_id)
        REFERENCES public.wiki_story_cards(id, agency_id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX wiki_story_links_agency_api_id_idx
    ON public.wiki_story_links(agency_id, COALESCE(legacy_id, id));
CREATE INDEX wiki_story_links_card_idx
    ON public.wiki_story_links(card_id, display_order);

WITH legacy_rows AS (
    SELECT '765'::text AS agency_code, '765_stories'::text AS legacy_table, s.*
    FROM public."765_stories" s
    UNION ALL
    SELECT '876', '876_stories', s.* FROM public."876_stories" s
    UNION ALL
    SELECT 'cg', 'cg_stories', s.* FROM public.cg_stories s
    UNION ALL
    SELECT 'ml', 'ml_stories', s.* FROM public.ml_stories s
    UNION ALL
    SELECT 'sidem', 'sidem_stories', s.* FROM public.sidem_stories s
    UNION ALL
    SELECT 'sc', 'sc_stories', s.* FROM public.sc_stories s
    UNION ALL
    SELECT 'gk', 'gk_stories', s.* FROM public.gk_stories s
), resolved AS (
    SELECT a.id AS agency_id, rows.id AS legacy_id, rows.idol_id,
           c.id AS category_id, rows.card_name, rows.subtitle, rows.image_file
    FROM legacy_rows rows
    JOIN public.agencies a ON a.code = rows.agency_code
    JOIN public.idols i ON i.id = rows.idol_id AND i.agency_id = a.id
    JOIN public.wiki_categories c
      ON c.agency_id = a.id AND c.name = rows.category
), grouped AS (
    SELECT agency_id, idol_id, category_id, card_name,
           (ARRAY_AGG(subtitle ORDER BY legacy_id))[1] AS subtitle,
           (ARRAY_AGG(image_file ORDER BY legacy_id))[1] AS image_file,
           MIN(legacy_id) AS first_legacy_id
    FROM resolved
    GROUP BY agency_id, idol_id, category_id, card_name
), ordered AS (
    SELECT grouped.*,
           ROW_NUMBER() OVER (
               PARTITION BY idol_id, category_id
               ORDER BY first_legacy_id, card_name
           ) - 1 AS display_order
    FROM grouped
)
INSERT INTO public.wiki_story_cards
    (agency_id, idol_id, category_id, card_name, subtitle, image_file, display_order)
SELECT agency_id, idol_id, category_id, card_name, subtitle, image_file,
       display_order::integer
FROM ordered
ORDER BY agency_id, idol_id, category_id, display_order;

WITH legacy_rows AS (
    SELECT '765'::text AS agency_code, '765_stories'::text AS legacy_table, s.*
    FROM public."765_stories" s
    UNION ALL
    SELECT '876', '876_stories', s.* FROM public."876_stories" s
    UNION ALL
    SELECT 'cg', 'cg_stories', s.* FROM public.cg_stories s
    UNION ALL
    SELECT 'ml', 'ml_stories', s.* FROM public.ml_stories s
    UNION ALL
    SELECT 'sidem', 'sidem_stories', s.* FROM public.sidem_stories s
    UNION ALL
    SELECT 'sc', 'sc_stories', s.* FROM public.sc_stories s
    UNION ALL
    SELECT 'gk', 'gk_stories', s.* FROM public.gk_stories s
), resolved AS (
    SELECT a.id AS agency_id, rows.legacy_table, rows.id AS legacy_id,
           rows.idol_id, c.id AS category_id, rows.card_name,
           rows.up_name, rows.video_title, rows.url, rows.subtitle, rows.image_file
    FROM legacy_rows rows
    JOIN public.agencies a ON a.code = rows.agency_code
    JOIN public.idols i ON i.id = rows.idol_id AND i.agency_id = a.id
    JOIN public.wiki_categories c
      ON c.agency_id = a.id AND c.name = rows.category
), linked AS (
    SELECT resolved.*, cards.id AS card_id,
           ROW_NUMBER() OVER (
               PARTITION BY cards.id ORDER BY resolved.legacy_id
           ) - 1 AS display_order
    FROM resolved
    JOIN public.wiki_story_cards cards
      ON cards.agency_id = resolved.agency_id
     AND cards.idol_id = resolved.idol_id
     AND cards.category_id = resolved.category_id
     AND cards.card_name = resolved.card_name
)
INSERT INTO public.wiki_story_links
    (agency_id, card_id, up_name, video_title, url, display_order,
     legacy_table, legacy_id, legacy_subtitle, legacy_image_file)
SELECT agency_id, card_id, up_name, video_title, url, display_order::integer,
       legacy_table, legacy_id, subtitle, image_file
FROM linked
ORDER BY agency_id, card_id, display_order;

SELECT setval(
    pg_get_serial_sequence('public.wiki_story_links', 'id'),
    GREATEST(
        COALESCE((SELECT MAX(id) FROM public.wiki_story_links), 0),
        COALESCE((SELECT MAX(legacy_id) FROM public.wiki_story_links), 0),
        1
    ),
    EXISTS (SELECT 1 FROM public.wiki_story_links)
);

DO $$
DECLARE
    legacy_count BIGINT;
    card_count BIGINT;
BEGIN
    SELECT
        (SELECT COUNT(*) FROM public."765_stories") +
        (SELECT COUNT(*) FROM public."876_stories") +
        (SELECT COUNT(*) FROM public.cg_stories) +
        (SELECT COUNT(*) FROM public.ml_stories) +
        (SELECT COUNT(*) FROM public.sidem_stories) +
        (SELECT COUNT(*) FROM public.sc_stories) +
        (SELECT COUNT(*) FROM public.gk_stories)
    INTO legacy_count;

    IF (SELECT COUNT(*) FROM public.wiki_story_links WHERE legacy_id IS NOT NULL)
        <> legacy_count THEN
        RAISE EXCEPTION 'Wiki story link backfill count differs from legacy rows';
    END IF;

    IF EXISTS (
        WITH legacy_rows AS (
            SELECT '765'::text AS agency_code, '765_stories'::text AS legacy_table, s.*
            FROM public."765_stories" s
            UNION ALL SELECT '876', '876_stories', s.* FROM public."876_stories" s
            UNION ALL SELECT 'cg', 'cg_stories', s.* FROM public.cg_stories s
            UNION ALL SELECT 'ml', 'ml_stories', s.* FROM public.ml_stories s
            UNION ALL SELECT 'sidem', 'sidem_stories', s.* FROM public.sidem_stories s
            UNION ALL SELECT 'sc', 'sc_stories', s.* FROM public.sc_stories s
            UNION ALL SELECT 'gk', 'gk_stories', s.* FROM public.gk_stories s
        ), legacy_projection AS (
            SELECT agency_code, legacy_table, id AS legacy_id, idol_id, category,
                   card_name, up_name, video_title, url, subtitle, image_file
            FROM legacy_rows
        ), normalized_projection AS (
            SELECT agencies.code AS agency_code, links.legacy_table, links.legacy_id,
                   cards.idol_id, categories.name AS category, cards.card_name,
                   links.up_name, links.video_title, links.url,
                   links.legacy_subtitle AS subtitle,
                   links.legacy_image_file AS image_file
            FROM public.wiki_story_links links
            JOIN public.wiki_story_cards cards
              ON cards.id = links.card_id AND cards.agency_id = links.agency_id
            JOIN public.wiki_categories categories
              ON categories.id = cards.category_id
             AND categories.agency_id = cards.agency_id
            JOIN public.agencies agencies ON agencies.id = cards.agency_id
            WHERE links.legacy_id IS NOT NULL
        )
        (SELECT * FROM legacy_projection EXCEPT SELECT * FROM normalized_projection)
        UNION ALL
        (SELECT * FROM normalized_projection EXCEPT SELECT * FROM legacy_projection)
    ) THEN
        RAISE EXCEPTION 'Wiki story normalized projection differs from legacy source rows';
    END IF;

    WITH legacy_groups AS (
        SELECT '765'::text AS agency_code, idol_id, category, card_name
        FROM public."765_stories"
        UNION
        SELECT '876', idol_id, category, card_name FROM public."876_stories"
        UNION
        SELECT 'cg', idol_id, category, card_name FROM public.cg_stories
        UNION
        SELECT 'ml', idol_id, category, card_name FROM public.ml_stories
        UNION
        SELECT 'sidem', idol_id, category, card_name FROM public.sidem_stories
        UNION
        SELECT 'sc', idol_id, category, card_name FROM public.sc_stories
        UNION
        SELECT 'gk', idol_id, category, card_name FROM public.gk_stories
    )
    SELECT COUNT(*) INTO card_count FROM legacy_groups;

    IF (SELECT COUNT(*) FROM public.wiki_story_cards) <> card_count THEN
        RAISE EXCEPTION 'Wiki story card backfill count differs from legacy groups';
    END IF;
END $$;

COMMENT ON TABLE public.wiki_story_cards IS
    'Runtime Wiki story cards. The seven legacy story tables remain read-only migration evidence.';
COMMENT ON COLUMN public.wiki_story_links.legacy_id IS
    'Agency-scoped legacy API ID; new links expose their generated id.';
COMMENT ON COLUMN public.wiki_story_links.legacy_subtitle IS
    'Original per-row value retained when duplicate legacy card rows disagree.';
COMMENT ON COLUMN public.wiki_story_links.legacy_image_file IS
    'Original per-row value retained when duplicate legacy card rows disagree.';
