-- ims:migration-phase: post-data

CREATE TABLE public.wiki_story_content_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    description TEXT NOT NULL DEFAULT '',
    display_order INTEGER NOT NULL CHECK (display_order >= 0),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    revision INTEGER NOT NULL DEFAULT 0 CHECK (revision >= 0)
);

CREATE TABLE public.wiki_story_source_platforms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    homepage_url TEXT NOT NULL DEFAULT '',
    description TEXT NOT NULL DEFAULT '',
    display_order INTEGER NOT NULL CHECK (display_order >= 0),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    revision INTEGER NOT NULL DEFAULT 0 CHECK (revision >= 0)
);

INSERT INTO public.wiki_story_content_types(name, description, display_order)
VALUES
    ('剧情', '卡片剧情、活动剧情或相关视频内容', 0),
    ('语音', '语音、广播或音频内容', 1),
    ('电话', '游戏内电话与通话内容', 2),
    ('文本专栏', '访谈、专栏、翻译与文字资料', 3);

INSERT INTO public.wiki_story_source_platforms
    (name, homepage_url, description, display_order)
VALUES
    ('Bilibili', 'https://www.bilibili.com', 'Bilibili 视频与专栏', 0),
    ('其他来源', '', '尚未归类或没有独立平台目录的来源', 1);

ALTER TABLE public.wiki_story_links
    ADD COLUMN content_type_id BIGINT,
    ADD COLUMN source_platform_id BIGINT;

UPDATE public.wiki_story_links
SET content_type_id = (
        SELECT id FROM public.wiki_story_content_types WHERE name = '剧情'
    ),
    source_platform_id = CASE
        WHEN LOWER(COALESCE(url, '')) LIKE '%bilibili.com/%'
          OR LOWER(COALESCE(url, '')) LIKE '%b23.tv/%'
        THEN (
            SELECT id FROM public.wiki_story_source_platforms
            WHERE name = 'Bilibili'
        )
        ELSE (
            SELECT id FROM public.wiki_story_source_platforms
            WHERE name = '其他来源'
        )
    END;

ALTER TABLE public.wiki_story_links
    ALTER COLUMN content_type_id SET NOT NULL,
    ALTER COLUMN source_platform_id SET NOT NULL,
    ADD CONSTRAINT wiki_story_links_content_type_fk
        FOREIGN KEY (content_type_id)
        REFERENCES public.wiki_story_content_types(id) ON DELETE RESTRICT,
    ADD CONSTRAINT wiki_story_links_source_platform_fk
        FOREIGN KEY (source_platform_id)
        REFERENCES public.wiki_story_source_platforms(id) ON DELETE RESTRICT;

CREATE INDEX wiki_story_links_content_type_idx
    ON public.wiki_story_links(content_type_id, card_id);
CREATE INDEX wiki_story_links_source_platform_idx
    ON public.wiki_story_links(source_platform_id, card_id);
