-- ims:migration-phase: post-data

CREATE TABLE public.wiki_story_cover_assets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agency_id BIGINT NOT NULL REFERENCES public.agencies(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    object_key TEXT NOT NULL UNIQUE,
    display_order INTEGER NOT NULL CHECK (display_order >= 0),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    revision INTEGER NOT NULL DEFAULT 0 CHECK (revision >= 0),
    UNIQUE (id, agency_id),
    UNIQUE (agency_id, name)
);

CREATE INDEX wiki_story_cover_assets_agency_order_idx
    ON public.wiki_story_cover_assets(agency_id, display_order, id);

ALTER TABLE public.wiki_story_cards
    ADD COLUMN cover_asset_id BIGINT,
    ADD CONSTRAINT wiki_story_cards_cover_asset_fk
        FOREIGN KEY (cover_asset_id, agency_id)
        REFERENCES public.wiki_story_cover_assets(id, agency_id)
        ON DELETE RESTRICT,
    ADD CONSTRAINT wiki_story_cards_single_cover_source_check
        CHECK (cover_asset_id IS NULL OR image_file IS NULL);

DROP INDEX public.wiki_story_cards_background_idx;
CREATE INDEX wiki_story_cards_background_idx
    ON public.wiki_story_cards(category_id, id)
    WHERE image_file IS NOT NULL OR cover_asset_id IS NOT NULL;

CREATE INDEX wiki_story_cards_cover_asset_idx
    ON public.wiki_story_cards(cover_asset_id)
    WHERE cover_asset_id IS NOT NULL;

COMMENT ON TABLE public.wiki_story_cover_assets IS
    'Agency-scoped reusable cover artwork for Wiki story cards.';
COMMENT ON COLUMN public.wiki_story_cards.cover_asset_id IS
    'Optional reusable agency cover; mutually exclusive with image_file.';
