-- ims:migration-phase: post-data

CREATE TABLE public.articles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_type TEXT NOT NULL,
    title TEXT NOT NULL,
    summary TEXT NOT NULL DEFAULT '',
    cover_url TEXT,
    body_json JSONB NOT NULL DEFAULT '{"type":"doc","content":[]}'::jsonb,
    body_html TEXT NOT NULL DEFAULT '',
    body_schema_version INTEGER NOT NULL DEFAULT 1,
    status TEXT NOT NULL DEFAULT 'draft',
    revision INTEGER NOT NULL DEFAULT 0,
    created_by BIGINT,
    updated_by BIGINT,
    published_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    published_at TIMESTAMPTZ,
    CONSTRAINT articles_content_type_check
        CHECK (content_type IN ('event', 'chronicle')),
    CONSTRAINT articles_status_check
        CHECK (status IN ('draft', 'published', 'archived')),
    CONSTRAINT articles_revision_check
        CHECK (revision >= 0),
    CONSTRAINT articles_body_schema_version_check
        CHECK (body_schema_version >= 1),
    CONSTRAINT articles_created_by_fkey
        FOREIGN KEY (created_by) REFERENCES public.users(id) ON DELETE SET NULL,
    CONSTRAINT articles_updated_by_fkey
        FOREIGN KEY (updated_by) REFERENCES public.users(id) ON DELETE SET NULL,
    CONSTRAINT articles_published_by_fkey
        FOREIGN KEY (published_by) REFERENCES public.users(id) ON DELETE SET NULL
);

CREATE INDEX articles_public_type_idx
    ON public.articles (content_type, status, published_at DESC, id DESC);

CREATE INDEX articles_updated_idx
    ON public.articles (status, updated_at DESC, id DESC);

CREATE TABLE public.article_assets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    article_id BIGINT NOT NULL,
    object_key TEXT,
    public_path TEXT NOT NULL,
    asset_usage TEXT NOT NULL,
    alt_text TEXT NOT NULL DEFAULT '',
    created_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT article_assets_usage_check
        CHECK (asset_usage IN ('cover', 'body')),
    CONSTRAINT article_assets_article_id_fkey
        FOREIGN KEY (article_id) REFERENCES public.articles(id) ON DELETE CASCADE,
    CONSTRAINT article_assets_created_by_fkey
        FOREIGN KEY (created_by) REFERENCES public.users(id) ON DELETE SET NULL,
    CONSTRAINT article_assets_object_key_unique UNIQUE (object_key),
    CONSTRAINT article_assets_public_path_unique UNIQUE (public_path)
);

CREATE INDEX article_assets_article_usage_idx
    ON public.article_assets (article_id, asset_usage, id);

ALTER TABLE public.events
    ADD COLUMN article_id BIGINT,
    ADD COLUMN kind TEXT NOT NULL DEFAULT 'notice',
    ADD COLUMN start_at TIMESTAMPTZ,
    ADD COLUMN end_at TIMESTAMPTZ,
    ADD COLUMN timezone TEXT NOT NULL DEFAULT 'Asia/Shanghai',
    ADD COLUMN venue_name TEXT,
    ADD COLUMN address TEXT,
    ADD COLUMN registration_url TEXT,
    ADD COLUMN event_status TEXT;

ALTER TABLE public.events
    ADD CONSTRAINT events_kind_check
        CHECK (kind IN ('event', 'notice')),
    ADD CONSTRAINT events_status_check
        CHECK (event_status IS NULL OR event_status IN (
            'scheduled', 'ongoing', 'ended', 'cancelled'
        )),
    ADD CONSTRAINT events_time_range_check
        CHECK (end_at IS NULL OR start_at IS NULL OR end_at >= start_at),
    ADD CONSTRAINT events_article_id_fkey
        FOREIGN KEY (article_id) REFERENCES public.articles(id) ON DELETE CASCADE;

CREATE UNIQUE INDEX events_article_id_unique
    ON public.events (article_id)
    WHERE article_id IS NOT NULL;

CREATE INDEX events_kind_status_id_idx
    ON public.events (kind, event_status, id DESC);

INSERT INTO public.articles (
    id,
    content_type,
    title,
    cover_url,
    body_json,
    body_html,
    status,
    revision,
    created_at,
    updated_at,
    published_at
)
SELECT
    e.id,
    'event',
    COALESCE(NULLIF(BTRIM(e.title), ''), '未命名活动'),
    NULLIF(BTRIM(e.image_url), ''),
    '{"type":"doc","content":[]}'::jsonb,
    '',
    CASE WHEN e.publication_state = 'ready' THEN 'published' ELSE 'draft' END,
    0,
    COALESCE(e.created_at, CURRENT_TIMESTAMP),
    COALESCE(e.created_at, CURRENT_TIMESTAMP),
    CASE WHEN e.publication_state = 'ready' THEN COALESCE(e.created_at, CURRENT_TIMESTAMP) END
FROM public.events e
ON CONFLICT (id) DO NOTHING;

SELECT setval(
    pg_get_serial_sequence('public.articles', 'id'),
    COALESCE(MAX(id), 1),
    MAX(id) IS NOT NULL
)
FROM public.articles;

UPDATE public.events e
SET article_id = e.id
WHERE e.article_id IS NULL
  AND EXISTS (SELECT 1 FROM public.articles a WHERE a.id = e.id);

CREATE TABLE public.chronicle_entries (
    article_id BIGINT PRIMARY KEY,
    occurred_on DATE,
    ended_on DATE,
    date_precision TEXT,
    source_type TEXT,
    source_event_id BIGINT,
    location TEXT,
    timeline_order INTEGER NOT NULL DEFAULT 0,
    live_source_id TEXT,
    live_title TEXT,
    live_date TEXT,
    live_time TEXT,
    live_location TEXT,
    live_detail_url TEXT,
    live_franchises JSONB NOT NULL DEFAULT '[]'::jsonb,
    live_brand_codes JSONB NOT NULL DEFAULT '[]'::jsonb,
    CONSTRAINT chronicle_entries_article_id_fkey
        FOREIGN KEY (article_id) REFERENCES public.articles(id) ON DELETE CASCADE,
    CONSTRAINT chronicle_entries_date_precision_check
        CHECK (date_precision IS NULL OR date_precision IN ('year', 'month', 'day')),
    CONSTRAINT chronicle_entries_source_type_check
        CHECK (source_type IS NULL OR source_type IN ('official', 'community')),
    CONSTRAINT chronicle_entries_date_range_check
        CHECK (ended_on IS NULL OR occurred_on IS NULL OR ended_on >= occurred_on),
    CONSTRAINT chronicle_entries_timeline_order_check
        CHECK (timeline_order >= 0),
    CONSTRAINT chronicle_entries_source_event_fkey
        FOREIGN KEY (source_event_id) REFERENCES public.events(id) ON DELETE SET NULL
);

CREATE INDEX chronicle_entries_timeline_idx
    ON public.chronicle_entries (occurred_on DESC, timeline_order, article_id DESC);

CREATE INDEX chronicle_entries_source_idx
    ON public.chronicle_entries (source_type, occurred_on DESC, article_id DESC);
