import type { WikiPublicIdol } from "~/lib/api"

// 灰姑娘女孩已付声偶像 folderName 名单（99 名，名单已冻结）。
// TODO(wiki-cv): 偶像表新增 cv 列后，用 cv 是否为空判断替换此名单。
export const CG_VOICED_IDOL_FOLDER_NAMES: ReadonlySet<string> = new Set([
  // Cute（30）
  "shimamura_uzuki",
  "nakano_yuka",
  "mizumoto_yukari",
  "shiina_noriko",
  "mimura_kanako",
  "kohinata_miho",
  "ogata_chieri",
  "igarashi_kyoko",
  "sakurai_momoka",
  "seki_hiromi",
  "munakata_atsumi",
  "fujimoto_rina",
  "yusa_kozue",
  "ichinose_shiki",
  "maekawa_miku",
  "miyamoto_frederica",
  "kobayakawa_sae",
  "saionji_kotoka",
  "futaba_anzu",
  "domyoji_karin",
  "koshimizu_sachiko",
  "abe_nana",
  "koga_koharu",
  "sakuma_mayu",
  "shiragiku_hotaru",
  "hayasaka_mirei",
  "otokura_yuuki",
  "tsujino_akari",
  "kurosaki_chitose",
  "shirayuki_chiyo",
  // Cool（35）
  "shibuya_rin",
  "kawashima_mizuki",
  "kamiya_nao",
  "kamijo_haruna",
  "araki_hina",
  "tada_riina",
  "sasaki_chie",
  "mifune_miyu",
  "fujiwara_hajime",
  "nitta_minami",
  "tachibana_arisu",
  "sagisawa_fumika",
  "yagami_makino",
  "layla",
  "asari_nanami",
  "matsunaga_ryo",
  "takagaki_kaede",
  "kanzaki_ranko",
  "hojo_karen",
  "sajo_yukimi",
  "shirasaka_koume",
  "shiomi_syuko",
  "wakiyama_tamami",
  "hayami_kanade",
  "ohishi_izumi",
  "morikubo_nono",
  "anastasia",
  "yamato_aki",
  "yuuki_haru",
  "ninomiya_asuka",
  "kiryu_tsukasa",
  "mochizuki_hijiri",
  "takafuji_kako",
  "sunazuka_akira",
  "hisakawa_hayate",
  // Passion（34）
  "honda_mio",
  "takamori_aiko",
  "ryuzaki_kaoru",
  "kimura_natsuki",
  "akagi_miria",
  "ohtsuki_yui",
  "himekawa_yuki",
  "kitami_yuzu",
  "ueda_suzuho",
  "oikawa_shizuku",
  "koseki_reina",
  "hoshi_syoko",
  "katagiri_sanae",
  "hori_yuko",
  "matoba_risa",
  "yorita_yoshino",
  "aiba_yumi",
  "jougasaki_mika",
  "jougasaki_rika",
  "hino_akane",
  "moroboshi_kirari",
  "totoki_airi",
  "natalia",
  "mukai_takumi",
  "ichihara_nina",
  "kita_hinako",
  "namba_emi",
  "hamaguchi_ayame",
  "murakami_tomoe",
  "sato_shin",
  "yumemi_riamu",
  "nanjo_hikaru",
  "eve_santaclaus",
  "hisakawa_nagi",
])

// 非偶像的特殊目录（如「活动剧情」）不属于偶像、没有付声概念，
// 在「隐藏未付声」时应始终保留，避免误伤剧情导航入口。
const CG_NON_IDOL_FOLDER_NAMES: ReadonlySet<string> = new Set(["event_story"])

export function shouldKeepCgIdol(idol: Pick<WikiPublicIdol, "folderName">) {
  return (
    CG_VOICED_IDOL_FOLDER_NAMES.has(idol.folderName) ||
    CG_NON_IDOL_FOLDER_NAMES.has(idol.folderName)
  )
}
