import type { WikiPublicIdol } from "~/shared/api"

interface WikiGroupDefinition {
  key: string
  name: string
  color: string
  iconUrl?: string
  members: readonly string[]
}

export interface WikiIdolGroup {
  key: string
  name: string
  color: string
  iconUrl?: string
  idols: WikiPublicIdol[]
}

const definitions: Readonly<Record<string, readonly WikiGroupDefinition[]>> = {
  "765PRO": [
    {
      key: "765pro",
      name: "765PRO",
      color: "#f34f6d",
      iconUrl: "/icon/765/765pro.webp",
      members: [
        "amami_haruka",
        "kisaragi_chihaya",
        "hoshii_miki",
        "hagiwara_yukiho",
        "takatsuki_yayoi",
        "kikuchi_makoto",
        "minase_iori",
        "shijou_takane",
        "akizuki_ritsuko",
        "miura_azusa",
        "futami_ami",
        "futami_mami",
        "ganaha_hibiki",
      ],
    },
    {
      key: "961pro",
      name: "961PRO",
      color: "#333333",
      iconUrl: "/icon/765/961pro.webp",
      members: ["leon", "shika", "okuzora_kohaku", "aya"],
    },
  ],
  "876PRO": [
    {
      key: "dearly-stars",
      name: "深情之星",
      color: "#ff79a1",
      iconUrl: "/icon/876/876.webp",
      members: ["hidaka_ai", "mizutani_eri", "akizuki_ryo"],
    },
    {
      key: "valiv",
      name: "vα-liv",
      color: "#7b68ee",
      iconUrl: "/icon/876/valiv.webp",
      members: ["tomori_manaka", "kamizuru_cosmo", "letora"],
    },
  ],
  灰姑娘女孩: [
    {
      key: "cg-special",
      name: "特殊",
      color: "#2681c8",
      iconUrl: "/icon/cg/special.webp",
      members: ["main_story", "event_story"],
    },
    {
      key: "cute",
      name: "Cute",
      color: "#ff5085",
      iconUrl: "/icon/cg/cute.webp",
      members: [
        "shimamura_uzuki",
        "nakano_yuka",
        "mizumoto_yukari",
        "shiina_noriko",
        "mimura_kanako",
        "kohinata_miho",
        "ogata_chieri",
        "igarashi_kyoko",
        "sakurai_momoka",
        "seki_hiromi",
        "munakata_atsumi",
        "fujimoto_rina",
        "yusa_kozue",
        "ichinose_shiki",
        "maekawa_miku",
        "miyamoto_frederica",
        "kobayakawa_sae",
        "saionji_kotoka",
        "futaba_anzu",
        "domyoji_karin",
        "koshimizu_sachiko",
        "abe_nana",
        "koga_koharu",
        "sakuma_mayu",
        "shiragiku_hotaru",
        "hayasaka_mirei",
        "otokura_yuuki",
        "tsujino_akari",
        "kurosaki_chitose",
        "shirayuki_chiyo",
        "fukuyama_mai",
        "imai_kana",
        "mochida_arisa",
        "okuyama_saori",
        "manaka_misato",
        "yanase_miyuki",
        "egami_tsubaki",
        "nagatomi_hasumi",
        "yokoyama_chika",
        "ohta_yuu",
        "ohara_michiru",
        "ohnuma_kurumi",
        "akanishi_erika",
        "matsubara_saya",
        "aihara_yukino",
        "yao_fueifuei",
        "momoi_azuki",
        "suzumiya_seika",
        "tsukimiya_miyabi",
        "hyodo_rena",
        "niwa_hitomi",
        "yanagi_kiyora",
        "imura_setsuna",
        "kusakabe_wakaba",
        "sakakibara_satomi",
        "anzai_miyako",
        "asano_fuka",
        "ohnishi_yuriko",
        "kudo_shinobu",
        "kurihara_nene",
        "clarice",
        "muramatsu_sakura",
        "ariura_kanna",
        "harada_miyo",
        "ikebukuro_akiha",
      ],
    },
    {
      key: "cool",
      name: "Cool",
      color: "#0062ff",
      iconUrl: "/icon/cg/cool.webp",
      members: [
        "shibuya_rin",
        "kawashima_mizuki",
        "kamiya_nao",
        "kamijo_haruna",
        "araki_hina",
        "tada_riina",
        "sasaki_chie",
        "mifune_miyu",
        "fujiwara_hajime",
        "nitta_minami",
        "tachibana_arisu",
        "sagisawa_fumika",
        "yagami_makino",
        "layla",
        "asari_nanami",
        "matsunaga_ryo",
        "takagaki_kaede",
        "kanzaki_ranko",
        "hojo_karen",
        "sajo_yukimi",
        "shirasaka_koume",
        "shiomi_syuko",
        "wakiyama_tamami",
        "hayami_kanade",
        "ohishi_izumi",
        "morikubo_nono",
        "anastasia",
        "yamato_aki",
        "yuuki_haru",
        "ninomiya_asuka",
        "kiryu_tsukasa",
        "mochizuki_hijiri",
        "takafuji_kako",
        "sunazuka_akira",
        "hisakawa_hayate",
        "kurokawa_chiaki",
        "matsumoto_sarina",
        "kirino_aya",
        "takahashi_reiko",
        "aikawa_chinatsu",
        "togo_ai",
        "mizuki_seira",
        "hattori_toko",
        "kiba_manami",
        "mizuno_midori",
        "furusawa_yoriko",
        "helen",
        "komuro_chinami",
        "takamine_noa",
        "ijuin_megumi",
        "hiiragi_shino",
        "kate",
        "sena_shiori",
        "ayase_honoka",
        "shinohara_rei",
        "wakui_rumi",
        "yoshioka_saki",
        "umeki_otoha",
        "kishibe_ayaka",
        "ujiie_mutsumi",
        "nishikawa_honami",
        "narumiya_yume",
        "fujii_tomo",
        "okazaki_yasuha",
        "matsuo_chizuru",
      ],
    },
    {
      key: "passion",
      name: "Passion",
      color: "#ff9d00",
      iconUrl: "/icon/cg/passion.webp",
      members: [
        "honda_mio",
        "takamori_aiko",
        "ryuzaki_kaoru",
        "kimura_natsuki",
        "akagi_miria",
        "ohtsuki_yui",
        "himekawa_yuki",
        "kitami_yuzu",
        "ueda_suzuho",
        "oikawa_shizuku",
        "koseki_reina",
        "hoshi_syoko",
        "katagiri_sanae",
        "hori_yuko",
        "matoba_risa",
        "yorita_yoshino",
        "aiba_yumi",
        "jougasaki_mika",
        "jougasaki_rika",
        "hino_akane",
        "moroboshi_kirari",
        "totoki_airi",
        "natalia",
        "mukai_takumi",
        "ichihara_nina",
        "kita_hinako",
        "namba_emi",
        "hamaguchi_ayame",
        "murakami_tomoe",
        "sato_shin",
        "nanjo_hikaru",
        "eve_santaclaus",
        "yumemi_riamu",
        "hisakawa_nagi",
        "namiki_meiko",
        "matsuyama_kumiko",
        "saito_yoko",
        "sawada_marina",
        "yaguchi_miu",
        "aino_nagisa",
        "manabe_itsuki",
        "ebihara_naho",
        "etou_misaki",
        "nishijima_kai",
        "zaizen_tokiko",
        "nonomura_sora",
        "hamakawa_ayuna",
        "wakabayashi_tomoka",
        "senzaki_ema",
        "soma_natsumi",
        "makihara_shiho",
        "sugisaka_umi",
        "kitagawa_mahiro",
        "mary_cochran",
        "komatsu_ibuki",
        "miyoshi_sana",
        "cathy_graham",
        "tsuchiya_ako",
        "shuto_aoi",
        "saejima_kiyomi",
      ],
    },
  ],
  百万现场: [
    {
      key: "ml-special",
      name: "特殊",
      color: "#3f51b5",
      iconUrl: "/icon/ml/special.webp",
      members: [
        "main_story",
        "event_story",
        "festival_story",
        "management_birthday",
        "aoba_misaki",
        "shika",
        "leon",
        "346_pro",
        "ichinose_shiki",
      ],
    },
    {
      key: "ml-allstars",
      name: "765PRO ALLSTARS",
      color: "#f34f6d",
      iconUrl: "/icon/ml/765pro.webp",
      members: [
        "amami_haruka",
        "kisaragi_chihaya",
        "hoshii_miki",
        "hagiwara_yukiho",
        "takatsuki_yayoi",
        "kikuchi_makoto",
        "minase_iori",
        "shijou_takane",
        "akizuki_ritsuko",
        "miura_azusa",
        "futami_ami",
        "futami_mami",
        "ganaha_hibiki",
      ],
    },
    {
      key: "princess-stars",
      name: "PRINCESS STARS",
      color: "#ea5b76",
      iconUrl: "/icon/ml/princess.webp",
      members: [
        "kasuga_mirai",
        "tanaka_kotoha",
        "satake_minako",
        "tokugawa_matsuri",
        "nanao_yuriko",
        "takayama_sayoko",
        "matsuda_arisa",
        "kousaka_umi",
        "nakatani_iku",
        "emily_stewart",
        "yabuki_kana",
        "yokoyama_nao",
        "fukuda_noriko",
      ],
    },
    {
      key: "fairy-stars",
      name: "FAIRY STARS",
      color: "#0074b3",
      iconUrl: "/icon/ml/fairy.webp",
      members: [
        "mogami_shizuka",
        "tokoro_megumi",
        "roco",
        "tenkubashi_tomoka",
        "kitazawa_shiho",
        "maihama_ayumu",
        "nikaido_chizuru",
        "makabe_mizuki",
        "momose_rio",
        "nagayoshi_subaru",
        "suou_momoko",
        "julia",
        "shiraishi_tsumugi",
      ],
    },
    {
      key: "angel-stars",
      name: "ANGEL STARS",
      color: "#fec352",
      iconUrl: "/icon/ml/angel.webp",
      members: [
        "ibuki_tsubasa",
        "shimabara_elena",
        "hakozaki_serika",
        "nonohara_akane",
        "mochizuki_anna",
        "kinoshita_hinata",
        "baba_konomi",
        "oogami_tamaki",
        "toyokawa_fuka",
        "miyao_miya",
        "shinomiya_karen",
        "kitakami_reika",
        "sakuramori_kaori",
      ],
    },
  ],
  SideM: [
    {
      key: "sidem-special",
      name: "特殊",
      color: "#0fbe94",
      iconUrl: "/icon/sidem/special.webp",
      members: ["reading_play", "growing_stars"],
    },
    {
      key: "sidem-units",
      name: "组合",
      color: "#0fbe94",
      iconUrl: "/icon/sidem/unit.webp",
      members: [
        "jupiter",
        "dramatic_stars",
        "altessimo",
        "beit",
        "w",
        "frame",
        "sai",
        "high_joker",
        "shinsoku_ikkon",
        "cafe_parade",
        "mofumofuen",
        "sem",
        "the_kogadou",
        "flags",
        "legenders",
        "c_first",
      ],
    },
  ],
  闪耀色彩: [
    {
      key: "sc-special",
      name: "特殊",
      color: "#8dbbff",
      iconUrl: "/icon/sc/special.webp",
      members: [
        "enza_units",
        "enza_festivals",
        "scsp_event",
        "live",
        "nanakusa_hazuki",
      ],
    },
    {
      key: "illumination-stars",
      name: "illumination STARS",
      color: "#ffca00",
      iconUrl: "/icon/sc/illumination_stars.webp",
      members: ["sakuragi_mano", "kazano_hiori", "hachimiya_meguru"],
    },
    {
      key: "lantica",
      name: "L'Antica",
      color: "#853998",
      iconUrl: "/icon/sc/l_antica.webp",
      members: [
        "tsukioka_kogane",
        "tanaka_mamimi",
        "shirase_sakuya",
        "mitsumine_yuika",
        "yukoku_kiriko",
      ],
    },
    {
      key: "houkago-climax-girls",
      name: "放学后Climax Girls",
      color: "#fa8333",
      iconUrl: "/icon/sc/houkago_climax_girls.webp",
      members: [
        "komiya_kaho",
        "sonoda_chiyoko",
        "saijo_juri",
        "morino_rinze",
        "arisugawa_natsuha",
      ],
    },
    {
      key: "alstroemeria",
      name: "Alstroemeria",
      color: "#ff699e",
      iconUrl: "/icon/sc/alstroemeria.webp",
      members: ["osaki_amana", "osaki_tenka", "kuwayama_chiyuki"],
    },
    {
      key: "straylight",
      name: "Straylight",
      color: "#af011c",
      iconUrl: "/icon/sc/straylight.webp",
      members: ["serizawa_asahi", "mayuzumi_fuyuko", "izumi_mei"],
    },
    {
      key: "noctchill",
      name: "noctchill",
      color: "#384d98",
      iconUrl: "/icon/sc/noctchill.webp",
      members: [
        "asakura_toru",
        "higuchi_madoka",
        "fukumaru_koito",
        "ichikawa_hinana",
      ],
    },
    {
      key: "shhis",
      name: "SHHis",
      color: "#008e74",
      iconUrl: "/icon/sc/shhis.webp",
      members: ["nanakusa_nichika", "aketa_mikoto"],
    },
    {
      key: "cometik",
      name: "CoMETIK",
      color: "#333333",
      iconUrl: "/icon/sc/cometik.webp",
      members: ["ikaruga_luca", "suzuki_hana", "ikuta_haruki"],
    },
    {
      key: "sc-collab",
      name: "联动",
      color: "#eb3ba6",
      iconUrl: "/icon/sc/collab.webp",
      members: ["ruby", "memcho", "arima_kana", "kurokawa_akane", "collab"],
    },
  ],
  学园偶像大师: [
    {
      key: "gk-special",
      name: "特殊",
      color: "#3f51b5",
      iconUrl: "/icon/gk/special.webp",
      members: ["main_story", "event_story", "s_card", "neo_asari"],
    },
    {
      key: "hatsuboshi-gakuen",
      name: "初星学园",
      color: "#ff9800",
      iconUrl: "/icon/gk/hatsuboshi_gakuen.webp",
      members: [
        "hanami_saki",
        "tsukimura_temari",
        "fujita_kotone",
        "arimura_mao",
        "katsuragi_liliya",
        "kuramoto_china",
        "shiun_sumika",
        "shinosawa_hiro",
        "himesaki_riha",
        "hanami_ume",
        "hataya_misuzu",
        "juo_sena",
        "amaya_tsubame",
      ],
    },
  ],
}

const classicBanners: Readonly<Record<string, string>> = {
  "765PRO": "765PRO ALLSTARS",
  "876PRO": "876PRO",
  灰姑娘女孩: "CINDERELLA GIRLS",
  百万现场: "百万现场 剧场时光",
  SideM: "315 Production",
  闪耀色彩: "283 Production",
  学园偶像大师: "初星学园",
}

export const classicAgencyIcons: Readonly<Record<string, string>> = {
  "765PRO": "/icon/765pro.webp",
  "876PRO": "/icon/876pro.webp",
  灰姑娘女孩: "/icon/cg.webp",
  百万现场: "/icon/ml.webp",
  SideM: "/icon/sidem.webp",
  闪耀色彩: "/icon/sc.webp",
  学园偶像大师: "/icon/gk.webp",
}

export function classicAgencyBanner(agency: string) {
  return classicBanners[agency] ?? agency
}

export function groupWikiIdols(
  agency: string,
  idols: WikiPublicIdol[]
): WikiIdolGroup[] {
  const agencyDefinitions = definitions[agency] ?? []
  const byIdentity = new Map<string, WikiPublicIdol>()
  const usedIds = new Set<number>()

  for (const idol of idols) {
    byIdentity.set(idol.folderName, idol)
    byIdentity.set(idol.name, idol)
  }

  const groups = agencyDefinitions.flatMap((definition) => {
    const members = definition.members.flatMap((identity) => {
      const idol = byIdentity.get(identity)
      if (!idol || usedIds.has(idol.id)) return []
      usedIds.add(idol.id)
      return [idol]
    })
    return members.length ? [{ ...definition, idols: members }] : []
  })
  const unmatched = idols.filter((idol) => !usedIds.has(idol.id))

  if (unmatched.length) {
    groups.push({
      key: "other",
      name: agencyDefinitions.length ? "事务所人员与其他" : agency,
      color: "#777777",
      idols: unmatched,
      members: [],
    })
  }

  return groups.map((group) => ({
    key: group.key,
    name: group.name,
    color: group.color,
    iconUrl: group.iconUrl,
    idols: group.idols,
  }))
}
