// Resource bindings are generated by `wrangler types`. The secret is an
// operator-provisioned binding and is the only augmentation not present in
// wrangler.jsonc.
export interface WorkerBindings extends CloudflareBindings {
    IMS_JWT_SECRET: string;
}
